import { fireEvent, render, waitFor } from "@testing-library/react";
import { Editor } from "@/components/editor";
import type { Transcript } from "@/lib/api";
import {
  captionText,
  paragraphs,
  TRANSCRIPT_HEADING,
  timestamp,
  transcriptEdit,
  transcriptSection,
} from "@/lib/transcript";

// The fetch is the one thing here that leaves the browser, and YouTube behind
// it. What these tests own is what the note ends up holding, not the HTTP.
const { fetchTranscript } = vi.hoisted(() => ({ fetchTranscript: vi.fn() }));
vi.mock("@/lib/api", () => ({ fetchTranscript }));

const VIDEO = "dQw4w9WgXcQ";
const LINK = `https://www.youtube.com/watch?v=${VIDEO}`;

function captions(lines: [number, string][], generated = false): Transcript {
  return { language: "en", generated, lines: lines.map(([start, text]) => ({ start, text })) };
}

describe("timestamps", () => {
  it("writes minutes and seconds under an hour", () => {
    expect(timestamp(0)).toBe("[00:00]");
    expect(timestamp(75.9)).toBe("[01:15]");
    expect(timestamp(3599)).toBe("[59:59]");
  });

  it("adds the hour once there is one", () => {
    expect(timestamp(3600)).toBe("[1:00:00]");
    expect(timestamp(3725)).toBe("[1:02:05]");
  });
});

describe("caption text", () => {
  it("decodes the entities YouTube leaves in", () => {
    expect(captionText("it&#39;s &quot;fine&quot; &amp; good")).toBe(`it's "fine" & good`);
  });

  it("joins the lines a caption wrapped onto", () => {
    expect(captionText("never gonna\ngive you up ")).toBe("never gonna give you up");
  });
});

describe("paragraphs", () => {
  it("keeps short captions together in one paragraph", () => {
    expect(
      paragraphs(
        captions([
          [0, "one"],
          [3, "two"],
          [6, "three"],
        ]).lines,
      ),
    ).toEqual(["[00:00] one two three"]);
  });

  it("ends a paragraph on a sentence once half a minute has gone", () => {
    const lines = captions([
      [0, "It starts."],
      [20, "Still early."],
      [31, "Now it ends."],
      [35, "Next one"],
    ]).lines;

    expect(paragraphs(lines)).toEqual([
      "[00:00] It starts. Still early. Now it ends.",
      "[00:35] Next one",
    ]);
  });

  it("ends a paragraph at a minute when no sentence does", () => {
    const lines = captions([
      [0, "no"],
      [30, "punctuation"],
      [60, "anywhere"],
      [62, "at all"],
    ]).lines;

    expect(paragraphs(lines)).toEqual(["[00:00] no punctuation anywhere", "[01:02] at all"]);
  });

  it("skips captions holding nothing", () => {
    expect(
      paragraphs(
        captions([
          [0, "\n"],
          [4, "words"],
        ]).lines,
      ),
    ).toEqual(["[00:04] words"]);
  });
});

describe("the section", () => {
  it("says which captions these are under the heading", () => {
    expect(transcriptSection(VIDEO, captions([[0, "hi"]], true))).toBe(
      [
        TRANSCRIPT_HEADING,
        "",
        `_Captions of \`${VIDEO}\`, in \`en\`, generated by YouTube._`,
        "",
        "[00:00] hi",
      ].join("\n"),
    );
  });

  function apply(text: string, section: string) {
    const { from, to, insert } = transcriptEdit(text, section);
    return text.slice(0, from) + insert + text.slice(to);
  }

  it("goes on the end of the note", () => {
    expect(apply("# Talk\n\nnotes\n\n", "## Transcript\n\nnew")).toBe(
      "# Talk\n\nnotes\n\n## Transcript\n\nnew\n",
    );
  });

  it("replaces the transcript already at the end", () => {
    expect(apply("# Talk\n\n## Transcript\n\nold\n\nolder\n", "## Transcript\n\nnew")).toBe(
      "# Talk\n\n## Transcript\n\nnew\n",
    );
  });

  it("replaces one in the middle, leaving the section after it", () => {
    expect(
      apply("# Talk\n## Transcript\nold\n### aside\n## Notes\nmine\n", "## Transcript\nnew"),
    ).toBe("# Talk\n## Transcript\nnew\n\n## Notes\nmine\n");
  });
});

describe("the transcript key", () => {
  // A block and not an arrow's value: a function handed back from `beforeEach`
  // is run as its teardown, and `mockReset` hands back the mock, which would
  // be called once more after every test.
  beforeEach(() => {
    fetchTranscript.mockReset();
  });

  function open(initialDoc: string) {
    const onChange = vi.fn();
    const onNotice = vi.fn();
    const { container } = render(
      <Editor initialDoc={initialDoc} onChange={onChange} onNotice={onNotice} />,
    );
    const editor = container.querySelector(".cm-content") as HTMLElement;
    return {
      editor,
      onNotice,
      doc: () => (onChange.mock.lastCall?.[0] as string | undefined) ?? initialDoc,
      press: (...keys: string[]) => {
        for (const key of keys) fireEvent.keyDown(editor, { key });
      },
    };
  }

  it("writes the transcript of the note's video on the end of the note", async () => {
    fetchTranscript.mockResolvedValue(
      captions([
        [0, "never gonna"],
        [2, "give you up"],
      ]),
    );
    const { press, doc } = open(`[talk](${LINK})\n`);

    press(" ", "c", "v");

    await waitFor(() => expect(doc()).toContain("[00:00] never gonna give you up"));
    expect(fetchTranscript).toHaveBeenCalledWith(VIDEO);
    expect(doc()).toBe(
      `[talk](${LINK})\n\n${transcriptSection(
        VIDEO,
        captions([
          [0, "never gonna"],
          [2, "give you up"],
        ]),
      )}\n`,
    );
  });

  it("takes the first video when the note links several", async () => {
    fetchTranscript.mockResolvedValue(captions([[0, "hi"]]));
    const { press } = open(`${LINK}\nhttps://youtu.be/aaaaaaaaaaa\n`);

    press(" ", "c", "v");

    await waitFor(() => expect(fetchTranscript).toHaveBeenCalledWith(VIDEO));
  });

  it("is taken back out by one undo", async () => {
    fetchTranscript.mockResolvedValue(
      captions([
        [0, "one"],
        [40, "two"],
        [90, "three"],
      ]),
    );
    const initial = `[talk](${LINK})\n`;
    const { press, doc } = open(initial);

    press(" ", "c", "v");
    await waitFor(() => expect(doc()).toContain(TRANSCRIPT_HEADING));
    press("u");

    await waitFor(() => expect(doc()).toBe(initial));
  });

  it("says so when the note links no video", () => {
    const { press, onNotice, doc } = open("just words\n");

    press(" ", "c", "v");

    expect(onNotice).toHaveBeenCalledWith("This note links no video");
    expect(fetchTranscript).not.toHaveBeenCalled();
    expect(doc()).toBe("just words\n");
  });

  it("passes the backend's sentence on when there is no transcript", async () => {
    fetchTranscript.mockRejectedValue(new Error("That video has no transcript"));
    const { press, onNotice, doc } = open(`${LINK}\n`);

    press(" ", "c", "v");

    await waitFor(() => expect(onNotice).toHaveBeenCalledWith("That video has no transcript"));
    expect(doc()).toBe(`${LINK}\n`);
  });
});
