/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report that the process is up. Deliberately does not touch the database.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Files
         * @description List every note in the vault as a relative POSIX path, sorted.
         *
         *     The client folds these into a folder tree; the server stays flat.
         */
        get: operations["list_files_api_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Terminals
         * @description Name every herdr session a terminal pane could attach to, sorted.
         *
         *     A listing of a directory the shell container owns, and nothing more. herdr
         *     is not run and the sessions are not touched, so this cannot say which are
         *     running; a name is enough for the prompt, and `herdr --session` attaches to
         *     a stopped session and starts a missing one alike.
         *
         *     An absent directory is not an error. The mount is optional and the shell
         *     container need not be up for the notebook to work, so the prompt falls back
         *     to a name typed by hand.
         */
        get: operations["list_terminals_api_terminals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch Page
         * @description Read one web page off the internet and hand it back unchanged.
         *
         *     The only endpoint that reads something other than the vault, and it writes
         *     nothing: what comes back is markup, and turning it into a note happens in
         *     the browser, where defuddle runs. That is where it has to run. defuddle is
         *     a DOM library, the browser has the DOM, and the alternative is a second
         *     extractor in Python that would read the same pages differently.
         *
         *     Fetching cannot happen there, though: a page from another origin is one the
         *     browser will request and not let the script read, so the request comes from
         *     here.
         *
         *     http and https and nothing else. The scheme is the trust boundary: `file://`
         *     would read this container's disk and hand it to the browser, and the check
         *     is made before anything is opened.
         *
         *     A page that could not be read is a 502 rather than the status the other end
         *     gave. The reader asked kasten for a note and kasten could not get one; a
         *     404 here would say the endpoint is missing.
         */
        get: operations["fetch_page_api_fetch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Files
         * @description Find every line in the vault containing `q`, ignoring case.
         *
         *     A literal match, not a regex and not a fuzzy one. The client ranks what
         *     comes back, which is what makes the finder feel fuzzy without asking a
         *     subsequence match to mean something over prose, where it matches everything.
         */
        get: operations["search_files_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Todos
         * @description Find every checkbox line and every time session line in the vault.
         *
         *     Candidate lines, not todos. Whether one of these is open, overdue or a
         *     subtask of the line above it is read on the client, off the same parser the
         *     editor draws a todo with, so the vault has one reader of the format rather
         *     than two in two languages.
         *
         *     Answers in search's shape, which is what lets the overlay rank these through
         *     the ranking it already has and open a note on the line it found.
         */
        get: operations["list_todos_api_todos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Report every change to the vault, kasten's own writes included.
         *
         *     Server-sent events, one `data:` line per changed note. The traffic runs one
         *     way, so this needs none of a WebSocket's machinery, and the browser
         *     reconnects on its own.
         *
         *     Nothing here knows which write was kasten's, and nothing tries to: the
         *     digest is what settles that at the other end, where the client holds the
         *     text it sent and can see its own save come back.
         *
         *     The stream carries no note text, only the path, what happened and a digest
         *     of what is now on disk. A client that wants the new content reads the note
         *     the way it always does.
         *
         *     The watcher lives as long as the connection. Starlette closes this generator
         *     when the client goes away, which ends the watch with it, so nothing is left
         *     running for a reader that has gone.
         */
        get: operations["stream_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read File
         * @description Read one note out of the vault.
         *
         *     Anything that is not a readable markdown file inside the vault is a 404,
         *     including paths that try to climb out of it.
         */
        get: operations["read_file_api_files__path__get"];
        /**
         * Save File
         * @description Write one note back to the vault.
         *
         *     Only over a note that is already there. Everything the read refuses is
         *     refused here too, and for the same reason, so a note you cannot open is a
         *     note you cannot overwrite.
         *
         *     The text is stamped on the way through, which dates the note and gives one
         *     written before kasten its id. The note on disk is read for that, so the id
         *     it already has outlives a client that sends the note back without one. What
         *     comes back is therefore what landed on disk rather than what arrived, and it
         *     is the only thing the client may believe: its own copy is a save behind from
         *     the moment it sends it.
         *
         *     The jj change is started before the write and the snapshot taken after, so
         *     the edit is bracketed by the history rather than trailing it. A vault that
         *     is not a jj repo skips both.
         */
        put: operations["save_file_api_files__path__put"];
        /**
         * Create File
         * @description Start a new note in the vault, empty unless a body comes with it.
         *
         *     This one says why it refused, unlike the read and the write: a 409 for a
         *     path already taken and a 400 for one the vault will not have. The user is
         *     about to retype the path and has to know which it was, and the one user
         *     behind oauth2-proxy learns nothing from a 409 that `GET /api/files` did not
         *     already hand them.
         *
         *     The path that comes back is the canonical spelling, not the URL's, because
         *     the client navigates to it and `ideas/./kasten.md` must not end up in the
         *     address bar.
         *
         *     The note starts with its frontmatter, so it has an id from the first moment
         *     it exists rather than from its first save. A body is written under that
         *     block and is stamped on the way through, the way a save's text is, so a
         *     body carrying a block of its own keeps the fields in it.
         *
         *     The body is optional because most creates have nothing to write: a note the
         *     reader is about to type is one they type themselves. It exists for the
         *     client that already knows the text, the periodic notes above all, which
         *     would otherwise have to save straight over the note they just made. That
         *     second write is a second event on `/api/events`, and one arriving while the
         *     reader types into the note it names reads as another writer.
         *
         *     The new note gets its own jj change, bracketed the way a save is. Both
         *     refusals return before any of that, so a bounced create leaves no change
         *     behind.
         */
        post: operations["create_file_api_files__path__post"];
        /**
         * Delete File
         * @description Take one note out of the vault, and hold it in the trash.
         *
         *     A `DELETE` that keeps the note is not a contradiction: what the vault holds
         *     is what these routes answer about, and the note stops being one of them the
         *     moment it moves. Nothing lists it, nothing searches it and no path reaches
         *     it, because everything here refuses a hidden folder.
         *
         *     A missing note is a 404, matching the read, the write and the move, so a
         *     note you cannot open is a note you cannot delete.
         *
         *     The links pointing at it are left alone. A `[[link]]` names a note rather
         *     than a place, the editor already draws one nothing answers to as missing,
         *     and rewriting the vault to say a note is gone would be the one edit a
         *     restore could not take back.
         */
        delete: operations["delete_file_api_files__path__delete"];
        options?: never;
        head?: never;
        /**
         * Move File
         * @description Give one note a new path, moving it between folders as well as renaming it.
         *
         *     `PATCH` rather than a `/rename` route because the path is the note's
         *     identity: `POST` starts a note, `PUT` replaces its text, and this changes
         *     where it lives. A verb in the URL would be the same thing spelled as a
         *     remote procedure call.
         *
         *     A missing source is a 404, matching the read and the write, so a note you
         *     cannot open stays a note you cannot move. The target names its refusal the
         *     way a create does, a 400 for a path the vault will not have and a 409 for
         *     one already taken, because the user is about to retype it and has to know
         *     which it was.
         *
         *     The text comes back read off disk rather than carried over from the client.
         *     Both the URL and the query key change on a move, and seeding the new one
         *     from here is what stops a note edited outside kasten arriving stale on the
         *     other side.
         */
        patch: operations["move_file_api_files__path__patch"];
        trace?: never;
    };
    "/api/folders/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Folder
         * @description Take one folder out of the vault, and every note under it with it.
         *
         *     Its own route rather than the one above, for the reason the folder's move
         *     has one: `/api/files/inbox` cannot mean the folder here and nothing at all
         *     on a `GET`. A source that is not a folder is a 404, a note at that path
         *     included, so the one way to delete a note stays the route above.
         *
         *     One entry in the trash, not one per note. The folder went in one rename and
         *     it comes back in one, so the thing you get back is the folder you deleted
         *     rather than a list of notes to put back yourself.
         */
        delete: operations["delete_folder_api_folders__path__delete"];
        options?: never;
        head?: never;
        /**
         * Move Folder
         * @description Give one folder a new path, and every note under it a new path with it.
         *
         *     Its own route rather than the one above, because a folder is not a note and
         *     `/api/files/inbox` cannot mean the folder on a `PATCH` and nothing at all on
         *     a `GET`. What the two share is the shape: the URL says where it lives now,
         *     the body where it should live from here on.
         *
         *     The refusals are the note's, read for a folder. A source that is not a
         *     folder is a 404, a note at that path included, so the one way to move a note
         *     stays the route above. The target names its refusal, a 400 for a path the
         *     vault will not have and a 409 for one already taken, because the user is
         *     about to retype it.
         *
         *     A target inside the source is a 400 too. A folder cannot hold itself, and
         *     `rename` raises on that rather than refusing, so it is caught here with the
         *     rest.
         *
         *     No content comes back. The notes under the folder are at new paths now, but
         *     they are unchanged, and the client works out where they went from the folder
         *     path alone.
         */
        patch: operations["move_folder_api_folders__path__patch"];
        trace?: never;
    };
    "/api/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Trash
         * @description Everything the trash is holding, newest first.
         *
         *     Read off the names in `.trash` rather than out of a list somebody has to
         *     keep in step. The name of an entry says where it came from and when it
         *     went, which is the whole record, so a note moved out of the trash by hand
         *     stops being on this list by the same act.
         */
        get: operations["read_trash_api_trash_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trash/{entry}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Restore Entry
         * @description Put one entry back where it was deleted from.
         *
         *     `PATCH`, and no body, for the reason a move is one: this changes where
         *     something lives, and where it should live is already written in the entry's
         *     own name. An entry the trash has not got is a 404, and a path something has
         *     taken since is a 409, which is the create's answer and the move's.
         */
        patch: operations["restore_entry_api_trash__entry__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Folder
         * @description One folder, as the vault spells it.
         *
         *     No content beside the path. A folder is the prefix of the notes under it and
         *     holds nothing of its own, so there is nothing else to answer with.
         */
        Folder: {
            /** Path */
            path: string;
        };
        /**
         * FolderMove
         * @description Where a folder should live from now on, and every note under it with it.
         */
        FolderMove: {
            /** Path */
            path: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness response.
         */
        Health: {
            /** Status */
            status: string;
        };
        /**
         * Note
         * @description One note, as it sits on disk.
         */
        Note: {
            /** Path */
            path: string;
            /** Content */
            content: string;
        };
        /**
         * NoteEdit
         * @description The text for a note. The path it belongs to comes from the URL.
         *
         *     A save carries one and a create may. Both write the same thing, the note's
         *     text below its block, so both read the same body.
         */
        NoteEdit: {
            /** Content */
            content: string;
        };
        /**
         * NoteMove
         * @description Where a note should live from now on. Where it lives today comes from the URL.
         */
        NoteMove: {
            /** Path */
            path: string;
        };
        /**
         * Page
         * @description One web page as it arrived, for the client to make a note out of.
         */
        Page: {
            /** Url */
            url: string;
            /** Html */
            html: string;
        };
        /**
         * Restored
         * @description Where a restored note or folder landed, which is where it was.
         */
        Restored: {
            /** Path */
            path: string;
        };
        /**
         * SearchHit
         * @description One line in the vault that matched, and enough to open the note on it.
         */
        SearchHit: {
            /** Path */
            path: string;
            /** Line */
            line: number;
            /** Text */
            text: string;
        };
        /**
         * TrashEntry
         * @description One deleted note or folder, waiting in the trash.
         */
        TrashEntry: {
            /** Entry */
            entry: string;
            /** Path */
            path: string;
            /**
             * Deleted
             * Format: date-time
             */
            deleted: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_files_api_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_terminals_api_terminals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    fetch_page_api_fetch_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_files_api_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_todos_api_todos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
        };
    };
    stream_events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_file_api_files__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_file_api_files__path__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_file_api_files__path__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NoteEdit"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_file_api_files__path__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_file_api_files__path__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteMove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_folder_api_folders__path__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_folder_api_folders__path__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderMove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Folder"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_trash_api_trash_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashEntry"][];
                };
            };
        };
    };
    restore_entry_api_trash__entry__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Restored"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
