/**
 * A video's captions, written into the note that links it.
 *
 * YouTube hands captions over a few words at a time, each with the second it
 * appears at. Nobody reads them that way, so they are joined into paragraphs
 * of about half a minute to a minute, each opening on the moment it starts:
 * prose to read and search, and a time to find the place in the video by.
 */

import type { EditorView } from "@codemirror/view";
import { fetchTranscript, type Transcript } from "@/lib/api";
import { noticeHandler } from "@/lib/image";
import type { Edit } from "@/lib/note-section";
import { noteVideos } from "@/lib/video";

/** The heading the transcript lives under, and the one a second press finds. */
export const TRANSCRIPT_HEADING = "## Transcript";

/**
 * How long a paragraph runs before it may end, and how long before it must.
 *
 * Between the two it waits for a caption that ends a sentence, so a paragraph
 * breaks where the speaker did when the captions carry punctuation. Generated
 * captions usually carry none, and those break at the upper bound.
 */
const SHORTEST_SECONDS = 30;
const LONGEST_SECONDS = 60;

/** A caption that finishes a sentence, a closing quote or bracket allowed after it. */
const SENTENCE_END = /[.!?]["')\]]?$/;

/** A heading at the transcript's own level or above, which is where its section ends. */
const SECTION_END = /^#{1,2} /;

/** `[mm:ss]`, or `[h:mm:ss]` once the video has passed its first hour. */
export function timestamp(seconds: number): string {
  const whole = Math.floor(seconds);
  const hours = Math.floor(whole / 3600);
  const minutes = Math.floor((whole % 3600) / 60);
  const rest = String(whole % 60).padStart(2, "0");
  return hours > 0
    ? `[${hours}:${String(minutes).padStart(2, "0")}:${rest}]`
    : `[${String(minutes).padStart(2, "0")}:${rest}]`;
}

/**
 * One caption as prose: entities decoded and its line breaks gone.
 *
 * The backend's library decodes the XML once, and YouTube escapes some text
 * twice, so an apostrophe can still arrive as `&#39;`. A parsed document's text
 * is the browser's own entity table rather than a list kept here, and nothing
 * in it runs. The breaks are where the caption wrapped on screen, which says
 * nothing about the sentence.
 */
export function captionText(raw: string): string {
  const decoded = new DOMParser().parseFromString(raw, "text/html").documentElement.textContent;
  return decoded.replace(/\s+/g, " ").trim();
}

/** The captions joined into paragraphs, each opening on the time it starts at. */
export function paragraphs(lines: Transcript["lines"]): string[] {
  const written: string[] = [];
  let start = 0;
  let words: string[] = [];

  for (const line of lines) {
    const text = captionText(line.text);
    // A caption of nothing but whitespace would put a double space in the
    // prose, or open a paragraph on nothing.
    if (text === "") continue;
    if (words.length === 0) start = line.start;
    words.push(text);

    const span = line.start - start;
    if (span >= LONGEST_SECONDS || (span >= SHORTEST_SECONDS && SENTENCE_END.test(text))) {
      written.push(`${timestamp(start)} ${words.join(" ")}`);
      words = [];
    }
  }
  if (words.length > 0) written.push(`${timestamp(start)} ${words.join(" ")}`);

  return written;
}

/**
 * The whole section: the heading, a line saying which captions these are, and
 * the paragraphs.
 *
 * The video is named in that line whatever the note holds. A note of lectures
 * links several, and one rule is simpler than a second one that notices.
 */
export function transcriptSection(id: string, transcript: Transcript): string {
  const source = transcript.generated ? "generated by YouTube" : "written by hand";
  const about = `_Captions of \`${id}\`, in \`${transcript.language}\`, ${source}._`;
  return [TRANSCRIPT_HEADING, "", about, "", paragraphs(transcript.lines).join("\n\n")].join("\n");
}

/**
 * The edit that puts the section in the note: over the one already there, or
 * on the end.
 *
 * Replacing rather than adding, so fetching again, for a better track or a
 * different video, leaves one transcript and not two. The section runs to the
 * next heading at its level or above, so a `###` someone wrote under it goes
 * with it, the way it would fold with it.
 */
export function transcriptEdit(text: string, section: string): Edit {
  const lines = text.split("\n");
  const at = lines.indexOf(TRANSCRIPT_HEADING);

  if (at === -1) {
    const trimmed = text.replace(/\n+$/, "");
    const gap = trimmed === "" ? "" : "\n\n";
    return { from: trimmed.length, to: text.length, insert: `${gap}${section}\n` };
  }

  let end = at + 1;
  while (end < lines.length && !SECTION_END.test(lines[end] ?? "")) end += 1;

  const from = lines.slice(0, at).join("\n").length + (at > 0 ? 1 : 0);
  if (end === lines.length) return { from, to: text.length, insert: `${section}\n` };
  const to = lines.slice(0, end).join("\n").length + 1;
  return { from, to, insert: `${section}\n\n` };
}

/**
 * Fetch the transcript of the note's video and write it into the note.
 *
 * One dispatch, so one `u` takes the whole section back out. The edit is
 * worked out against the note as it stands when the answer lands rather than
 * as it stood when the key was pressed, the way a pasted image is placed.
 *
 * ponytail: the first video the note links, not the one the video pane is
 * showing. The pane keeps its place in the list to itself, in `video-pane.tsx`,
 * and the editor has no way to it; lifting it to the route and handing it down
 * on a facet, the way `noticeHandler` travels, is the upgrade.
 */
export async function writeTranscript(view: EditorView): Promise<void> {
  const notice = view.state.facet(noticeHandler);
  const id = noteVideos(view.state.doc.toString())[0];
  if (id === undefined) {
    notice?.("This note links no video");
    return;
  }

  let transcript: Transcript;
  try {
    transcript = await fetchTranscript(id);
  } catch (error: unknown) {
    // Typed and not bare, the way `fileImage` catches: a dropped connection
    // rejects with no response and no sentence of the backend's.
    notice?.(error instanceof Error ? error.message : "The transcript did not arrive");
    return;
  }

  // The note may have been closed while YouTube answered, and its view torn
  // down with it. There is nothing on screen to write into.
  if (!view.dom.isConnected) return;
  const edit = transcriptEdit(view.state.doc.toString(), transcriptSection(id, transcript));
  view.dispatch({ changes: edit });
}
